### ISSUE TITLE
[Bug]: Conflicting PHP libraries from different apps.

### ISSUE THREAD

**Issue by mikemuller** [beyondcode/herd-community#1071]
### Platform

macOS

### Operating system version

14.7

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.11.1

### Bug description

Using 2 different applications for local development and the PHP libraries conflic due to the PATH export for php.
I use Local by Flywheel for Wordpress Local development and the use Herd for other PHP development. When I install Herd this line is added to the .zshrd file: # export PATH="/Users/mikemuller/Library/Application Support/Herd/bin/":$PATH

The problem is this export breaks Local by Flywheel because it's looking in a different location for the PHP it installs. I can't change that path. Will Herd break if I comment that line out and leave the PHP path pointing at the Local version? Or is there a way to make the export PATH line conditional based on the application?

**Comment by mpociot** [comment]
You can't really make the export conditional. 
But you can also use Herd to develop WordPress applications locally. 

If you remove the path entry, some features probably will be broken in the app. 
You could otherwise try and load Local's path adjustments after Herds. 

Either way, this is not really the intended way of using Herd and you will run into some problems with both dev environments running in parallel.
