### ISSUE TITLE
[Bug]: Isolated PHP version is not used in VSCode.

### ISSUE THREAD

**Issue by MGeurts** [beyondcode/herd-community#1205]
### Platform

Windows

### Operating system version

Windows 11 24H2

### System architecture

Intel (x86)

### Herd Version

1.0.13

### PHP Version

PHP 8.4 (isolated) and 8.3.14 (global)

### Bug description

When configuring certain sites with a non-global PHP version, still the global version is used in VSCode.

![HERD - PHP Versions](https://github.com/user-attachments/assets/a4e48d6b-ead9-4c35-afa2-3ca097c30b19)

Although the site **genealogy.test** is set to use PHP 8.4, in VSCode it still uses the global PHP version 8.3.14.

![HERD - PHP Versions - 2](https://github.com/user-attachments/assets/a28902e3-e86e-4823-bf1b-92f8af00d150)

**Comment by MGeurts** [comment]
The same happens with node.js versions.

**Comment by mpociot** [comment]
Well this is a configuration issue within VSCode then. 
The isolation feature allows you to run 
"herd php" or "herd composer" commands so that they will use the project specific PHP version. 

For node, you can run "npm use" in a folder that is isolated to automatically switch to its node version. 

You would need to configure VSCode yourself to use specific PHP binaries as that's out of the scope of Herd.
