### ISSUE TITLE
[Bug]: Resolving Herd Functionality Issue After Computer Sleep Mode 

### ISSUE THREAD

**Issue by dalholm** [beyondcode/herd-community#126]
### Operating system version

macOS Ventura 13.4.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.1.6 build 13

### PHP Version

PHP 8.2.8

### Bug description

I use Raycast to put my computer into sleep mode. However, each time I begin a new day, I have to restart the computer to get Herd functioning again. 

I have tried to "stop all" and start again but the browser just spinning resolves with "ERR_NAME_NOT_RESOLVED"

any ideas ?

**Comment by mpociot** [comment]
Can you reproduce this every time you put your computer into sleep mode? No matter how long?

Are all services still running in the UI?
The name not resolved error comes from the DNS, which should still work just fine.

What happens if you try to ping a local domain via the terminal? Like `ping some-site.test`?

**Comment by dalholm** [comment]
@mpociot yes, every time overnight. I will try ping tomorrow.

**Comment by dalholm** [comment]
@mpociot when i ping i get `Unknown host`. I tried restarting all services both by ui and cli. But when i restart my computer it all works again.

**Comment by mpociot** [comment]
Do you see any log output/errors when starting/restarting DNSMasq in this case?
I'm still unable to reproduce this.

Also I'd like to know if this error happens every time you put your computer into sleep mode (even if just for a minute)
