### ISSUE TITLE
[Bug]: Wordpress doesn't generate debug.log through Herd

### ISSUE THREAD

**Issue by Rvervuurt** [beyondcode/herd-community#134]
### Operating system version

macOS Ventura 13.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.2.0 (build: 14)

### Bug description

When running a Wordpress installation in Herd with DBngin, Wordpress doesn't/can't write debug.log anymore.

### Steps to reproduce

1. Create database in DBngin
2. Install Wordpress in the database
3. Activate debug-logging
4. Add the following snippet to your `functions.php`:
```
if (!function_exists('write_log')) {

    function write_log($log) {
        if (true === WP_DEBUG) {
            if (is_array($log) || is_object($log)) {
                error_log(print_r($log, true));
            } else {
                error_log($log);
            }
        }
    }

}
write_log('hello');
```
5. See that nothing happens

**Comment by marcorieser** [comment]
Can confirm that the log does not get generated. My current workaround is to log the errors in Ray (https://spatie.be/docs/ray/v1/usage/wordpress#content-displaying-wordpress-errors)

**Comment by mpociot** [comment]
You can just change the FPM config file to your liking in this case 👍

**Comment by Rvervuurt** [comment]
Where do I find this fpm config file?

**Comment by nkb-bd** [comment]
@Rvervuurt check /Users/{user_name}/Library/Application Support/Herd/Log/php-fpm.log

**Comment by marcorieser** [comment]
Maybe this helps somebody in the future although I'm not completely sure if got it right.

It seems that values defined by `php_admin_value` are not overwritable by `ini_set()`.  That's what WordPress is trying to do to set `error_log` to `/wp-content/debug.log`. 

In my case: `php_admin_value[error_log] = /Users/{user_name}/Library/Application Support/Herd/Log/php-fpm.log` in `/Users/{user_name}/Library/Application Support/Herd/config/fpm/8.3-fpm.conf`.

Switching `php_admin_value[error_log] = ...` to `php_value[error_log] = ...` seems to set the default log path but allows to overwrite it by `ini_set()`.

**Comment by renggasaksono** [comment]
@marcorieser perfect solution, thanks!

**Comment by ImtiazEpu** [comment]
Hello everyone, 

If you're running WordPress on **Laravel Herd** and debug.log is not writing, the problem is Herd's php_admin_value[error_log] override in PHP-FPM. WordPress tries to redirect logs, but can't.

I built a plugin to fix this:

🔗 [WP Debug Log Enforcer](https://github.com/imtiazepu/wp-debug-log-enforcer)

It:

-   Ensures all PHP & WordPress errors are written into wp-content/debug.log

-   Logs failed wp_mail() attempts

-   Adds a write_log() helper with timestamp + file/line for custom debugging

No need to touch Herd configs. Just install, activate, and you'll see logs where you expect them. ✅

---

If you like it, please ⭐ the repo and feel free to contribute! 🙌
