### ISSUE TITLE
[Feature Request]: Avoid NOPASSWD sudo, improve privilege elevation process

### ISSUE THREAD

**Issue by kraynel** [beyondcode/herd-community#204]
### Feature Description

Thanks for the project, very useful!

Herd installation is currently creating a `/private/etc/sudoers.d/herd` allowing root execution, without password, of everything in `/Applications/Herd.app/Contents/Resources/*` plus native binaries `/usr/bin/security` and `/bin/kill`. This triggers warning in my company security policy which prevents use of `NOPASSWD` sudo.

This is probably needed to setup domain redirection with dnsmasq and run nginx on ports 80 and 443, but is not ideal in my opinion.

Would it be possible to setup dnsmasq once at startup and run nginx on a non restricted port by default? Or maybe use something more MacOS native than sudo to get elevated privileges?

Thanks!

### Is this feature valuable for other users as well and why?

This would increase the global security of the application and decrease attack surface.

**Comment by mpociot** [comment]
As we by default open ports that require sudo permissions, this is the most developer-friendly way to solve this (and also the way that Laravel Valet handles this).
If you want, you can modify the nginx config to use different ports and modify the contents of the sudoers file as needed.

**Comment by jfe-imarc** [comment]
Hi @mpociot @sschlein @mechelon , I'm raising this one again because I'm not sure the severity of this issue was clearly identified here. This sudoers rule allows for passwordless privilege escalation for any program running under the MacOS user account that Laravel Herd was installed under.

Simple test you can run after a clean install:
```
cd /Applications/Herd.app/Contents/Resources 
echo "#\!/bin/bash\nwhoami" > whoami.sh
chmod 755 whoami.sh
sudo ./whoami.sh
```


Ran after a fresh install of the DMG:
```
~ % cd /Applications/Herd.app/Contents/Resources
Contents/Resources % echo "#\!/bin/bash\nwhoami" > whoami.sh
Contents/Resources % chmod 755 whoami.sh
Contents/Resources % sudo ./whoami.sh
root
Contents/Resources % ls -alh /Applications/Herd.app/Contents/Resources
total 379400
drwxr-xr-x@ 30 REDACTED_USERNAME  admin   960B Feb 21 09:04 .
drwxr-xr-x@ 10 REDACTED_USERNAME  admin   320B Feb 13 09:13 ..
(...)
```

I understand that another piece of software may also install with a similar sudoers rule, but that isn't relevant to the immediate threat having a default installation of Laravel Herd creates for your users. 

My first suggestion for remediation would be to always prompt users for a password when wanting to bind to ports 80 and 443. If that's off the table, a second option would be to restrict the sudoers rule to only the specific binaries or scripts in the Resources directory and ensure that those executables are only writable by `root`. Can you review, test, and let me know if there's anything else I could do to help bring this to a secure resolution?
