### ISSUE TITLE
[Bug]: "message": "CSRF token mismatch." on legacy Laravel app

### ISSUE THREAD

**Issue by nezaboravi** [beyondcode/herd-community#255]
### Operating system version

macOS Sonoma Version 14.1.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.3.1 Build 18

### PHP Version

PHP 8.2.13 (cli) (built: Nov 24 2023 00:13:09) 

### Bug description

I ll do my best to explain.
I got some old app to maintain. It's a mess. It was built on Laravel 7.

1. I tried using it with herd by setting php version to 7 for this app. Page would load and when I want to login, I get message "CSRF token mismatch." 
Please understand that this is not my first app, so I am very well aware of what can cause this message. I have checked all known possible reasons. Do not stop reading here :)
2. I have upgraded Laravel to 10 and php to 8.2 for this app. Still got same error: "CSRF token mismatch."
3. I have removed Herd and I installed Laravel Valet. Everything worked, no "CSRF token mismatch." anymore. 
ok I know Herd is using valet. 

So, bottom line is that **this Laravel app will work on Valet,** it does **work also on production** servers, dev servers, on my **Laravel forge provided** dev server as well, and **only throws "CSRF token mismatch." on Herd**.

I will be happy to provide any more details to help beyondcode team you to check on your own local installation. 

Forgot to mention. I have installed a brand new computer, latest Sonoma on it, latest Herd on it in hope that maybe my old installation was somehow corrupted, but I got same behavior and app is not working using Herd. 

@mpociot if you would like to see and try it I am happy to provide you a link to Laravel forge provisioned app web url and user/pass to login and see that everything works there, as well as a git repo so you can try on your local under Herd. 
On my local I now don't have valet, only Herd.

### Steps to reproduce

Login in app throws the error.

**Comment by mpociot** [comment]
Are you able to reproduce this issue in a fresh Laravel app? Would be great if you could share a simple example repo that causes this issue for you.

**Comment by nezaboravi** [comment]
@mpociot i have aded you to git repo that has this issue and wrote a simple readme for you to run it locally- if possible on machine that does not have valet, only Herd. 

I am not able to reproduce this in fresh laravel app.

**Comment by mpociot** [comment]
@nezaboravi this issue could be related to #137 
Please adjust your php.ini file accordingly :)

**Comment by nezaboravi** [comment]
Thank you @mpociot , that fixed it!

**Comment by akulmehta** [comment]
I just wanted to document a similar issue I faced on Windows- it was related to the setting for the `sys_temp_dir` pointing to my windows `Temp` directory, and php not having sufficient permission to create temporary files. 

My app had the following symptoms:
1. Livewire was showing a json error in the browser console:

```console
Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

due to the response being received from the server as a 419 expired page.

2. When I looked at the logs it showed a CSRF token mismatch error.

3. When I looked at the `php artisan serve` console it showed the lines:

```console
   WARN  PHP Warning: PHP Request Startup: Unable to create temporary file, Check permissions in temporary files directory. in Unknown on line 0.

   WARN  PHP Warning: PHP Request Startup: POST data can't be buffered; all data discarded in Unknown on line 0.
```

The solution as @mpociot  pointed out was to go to the php.ini file used by Herd and changing/uncommenting the `sys_temp_dir` to point to `"/tmp"` - and that fixed it.

I hope this helps anyone else who faces this issue.
