### ISSUE TITLE
[Bug]: Herd not started after update

### ISSUE THREAD

**Issue by bpartner** [beyondcode/herd-community#325]
### Operating system version

macOS Sonoma 14.3

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.4.0

### Bug description

![image](https://github.com/beyondcode/herd-community/assets/11382071/1576ddf7-a09b-47a6-a487-0775f09c69d0)
![image](https://github.com/beyondcode/herd-community/assets/11382071/d8936935-7aa8-4bb5-b13a-cf7108124b52)
![image](https://github.com/beyondcode/herd-community/assets/11382071/dc78e9eb-43df-40ed-9be3-b5a81f9a44e2)

**Comment by luanrodrigues** [comment]
same here

**Comment by sschlein** [comment]
Can you please check your `herd.json` and maybe post it here? It shouldn't have sensitive information in it and I know from at least one other case, where a port (of Herd Pro) was set to a very high number >90k that broke the app until it was fixed in the json file. Maybe there is something else broken in your file, even if you aren't using Herd Pro.

It's at: `/Users/YOUR-USERNAME/Library/Application Support/Herd/config`

**Comment by bpartner** [comment]
config.json
{
    "tld": "test",
    "loopback": "127.0.0.1",
    "paths": [
        "/Users/bpartner/Library/Application Support/Herd/config/valet/Sites/",
        "/Users/bpartner/Herd/"
    ],
    "share-tool": "expose"
}

old herd.json
{"lastSite":"\/Users\/bpartner\/Projects\/php\/test"}

When running through the command line, each operation takes a very long time to complete. 
Is there any possibility to downgrade the version?

**Comment by mpociot** [comment]
@bpartner Do you still experience the issue?
The CLI commands communicate with the GUI app in order to retrieve certain settings, so I'm sure that's related.

Downgrading is possible, but not necessarily recommended

**Comment by bpartner** [comment]
Yes, the issue is still there. So far, I've switched to the valet. :(

**Comment by sschlein** [comment]
(If you can't find your Herd menubar icon, it's probably hidden because you have way to muchs tuff in your menu bar)
