### ISSUE TITLE
[Bug]: Herd Pro doesn't override the mail server settings in .env (Herd Pro)

### ISSUE THREAD

**Issue by didi955** [beyondcode/herd-community#664]
### Platform

Windows

### Operating system version

Windows 11 (23H2 22631.3447)

### System architecture

Windows

### Herd Version

1.1.0

### PHP Version

PHP 8.3.6

### Bug description

After changing the mail server's port to 587 for example and setup a new Laravel project with the "Laravel new" command. The .env file remains unchanged according to the Herd Mail server informations  despite the "Herd Pro set up your mailbox at Test. Your application is ready to send mails now!" message in the terminal.

However, in the Mail Tab informations are correct.
![image](https://github.com/beyondcode/herd-community/assets/45293702/dca1f025-b7ed-4584-8949-616e49a5a0a0)

.env content : 

MAIL_MAILER=log
MAIL_HOST=127.0.0.1
MAIL_PORT=2525
MAIL_USERNAME="Test"
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS="hello@example.com"
MAIL_FROM_NAME="${APP_NAME}"

### Steps to reproduce

- Change the default Mail server port
- Create a new Laravel project

**Comment by mechelon** [comment]
Just to clarify this: You have set up the Laravel app first, and after that changed the port of the mailserver? Then this expected behaviour because the installer always takes the **current** Mailserver `.env` information and writes it to the `.env` of the Laravel app during installation. It will **not** update the Mailserver configuration in every applications `.env` when you change it.

**Comment by didi955** [comment]
No, i have created the laravel app after with Laravel Installer. The Herd mail server settings was already changed.
