### ISSUE TITLE
[Feature Request]: Option to remove sites

### ISSUE THREAD

**Issue by dekts** [beyondcode/herd-community#72]
### Feature Description

Many unnecessary sites were established as I converted the herd from the valet. If we could remove a site from the list, that would be nice.

e.g. 

http://.docker.test
http://.git.test
http://.vscode.test
http://app.test

and a lot more in a single undertaking.

### Is this feature valuable for other users as well and why?

They were able to either erase the sites or regenerate them, yes.

**Comment by mpociot** [comment]
The sites are basically just parked/linked folders from your configured Herd paths.
If you want to remove a site it's better if you manually delete the folder (and be sure that it doesn't contain something you wanna keep) instead of doing it via a button in the UI.

That being said: Simply delete the folder and the site is gone too 👍
