### ISSUE TITLE
[Bug]: Permission problems with upload files for windows user.

### ISSUE THREAD

**Issue by Nothing-Works** [beyondcode/herd-community#736]
### Platform

Windows

### Operating system version

Win 10

### System architecture

Windows

### Herd Version

1.6.1

### PHP Version

8.3.7

### Bug description

The `sys_temp_dir` and `upload_tmp_dir` are not set in `php.ini` and for Windows users then the default location will be `C:\windows` and I assume most of people will face permission problems, which will result in "file upload error - unable to create a temporary file in unknown on line 0" when you are trying to upload file.

so I assume, we could either set the values or have the value can be configured from the UI directly just like file size 
![image](https://github.com/beyondcode/herd-community/assets/18606648/06e75da5-a125-4a89-8f18-d30b7200076c)

**Comment by mpociot** [comment]
I think it's easy enough to modify your php.ini file in case you want to override and customize these settings.

**Comment by dev-mo-ali** [comment]
how to fix this issue on Windows ?

**Comment by dev-mo-ali** [comment]
> how to fix this issue on Windows ?

https://stackoverflow.com/questions/18395163/warning-file-upload-error-unable-to-create-a-temporary-file-in-unknown-on-lin

Latest Answer 2025
The problem is caused by the php.ini configuration. In this case, I'm using [Laravel Herd](https://herd.laravel.com/) as my PHP development environment, but other environments (Laragon, XAMPP, etc.) should be the same, only the steps to open the php.ini file may differ.

Follow this step:

open laravel herd
go to PHP menu
right click on php version
select "open php.ini directory"
open and edit your php.ini file
uncomment and set your sys_temp_dir
// before
;sys_temp_dir = "/tmp"

// after
sys_temp_dir = "C:\Users\<YOUR_USERNAME>\AppData\Local\Temp"
