### ISSUE TITLE
[Bug]: Two folders with the same name

### ISSUE THREAD

**Issue by KoljaL** [beyondcode/herd-community#754]
### Platform

macOS

### Operating system version

macOS 14

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.0.6

### PHP Version

7.4

### Bug description

I have the following structure for my projects:
```
code
  Project1
    API
    Frontend
  Project2
    API
    Frontend
```

There are many projects in the code folder, so i have to set every project as an extra site to Herd.   
But only the first API folder will get an URL. 

### Steps to reproduce

Create a folder structure like shown and add both projects to Herd

**Comment by sschlein** [comment]
You could either name the folders:

api.project1
frontend.project1
api.project2
frontend.project2

or use `herd link` for every folder and set an url manually instead of running `herd park` in every project directory.

Adding all projects via the general settings doesn't work because Herd has no idea which project you want to access, so it serves the first one.

**Comment by KoljaL** [comment]
THX, I didn't know about herd link.

Maybe add this feature in the GUI, or make a hint in the docs. 

Best regards

Kolja

**Comment by sschlein** [comment]
I've added that to the docs (but still needs to be deployed later)
