### ISSUE TITLE
[Bug]: Postgres with admin permissions

### ISSUE THREAD

**Issue by kyloknight** [beyondcode/herd-community#755]
### Platform

Windows

### Operating system version

Windows 11 (10.0.22631 Build 22631)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.6.1

### Bug description

**Herd cannot start on windows. I get this error:** 

Execution of PostgreSQL by a user with administrative permissions is not
permitted.

The server must be started under an unprivileged user ID to prevent
possible system security compromises.  See the documentation for
more information on how to properly start the server.

Starting PostgreSQL (PostgreSQL) on port 5432 with datapath 02298a64-ccce-4ceb-ba92-2157703e736aExecution of PostgreSQL by a user with administrative permissions is not
permitted.

The server must be started under an unprivileged user ID to prevent
possible system security compromises.  See the documentation for
more information on how to properly start the server.

I found solutions online if I install PostgreSQL separate from Herd, but that is not ideal, I prefer everything centralized. Is there a solution to get this to work while staying logged in using my administrative account that I have everything installed on?

**Comment by sschlein** [comment]
@kyloknight Do you run Herd as an administrator? Herd should usually run from your normal user account and not be started as administrator. It aks for admin permissions in some cases and also has a Helper service for performing tasks that require these permissons (like writing to your hosts file).

Running directly as admin is not supported because of these side effects.
