### ISSUE TITLE
[Bug]: MySQL Database services deleted after create a Postgre service

### ISSUE THREAD

**Issue by wagnerfnds** [beyondcode/herd-community#852]
### Platform

macOS

### Operating system version

Sonoma 14.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.7.1 (Build 28)

### Bug description

Hi guys, when we have a MySQL service and we want to run another database service like Postgre 16, it deletes the MySQL service with all databases. If this should be the normal behavior, so at least could have a confirmation alert.

**Comment by mpociot** [comment]
This is definitely not a normal behavior. 
So you still see the MySQL service in your list of services but it's deleted?
How can I reproduce this, as I have pretty much every available service running

**Comment by wagnerfnds** [comment]
Yes, I continued to see my MySQL service and also the newly created Postgres, but Postrgres did not start automatically or manually and all MySQL databases were deleted as if a new MySQL service had been created.

I deleted the Postgres service (which didn't start) and tried creating it again to reproduce the error, this time the port was already in use. When checking what was running on the port I found a strange MySQL service running on the Postgres port.

I don't have any local installation of MySQL or Postgres, only the Herd services.

I'll attach some images that might help.

<img width="917" alt="Screenshot 2024-06-29 at 10 52 24" src="https://github.com/beyondcode/herd-community/assets/19960361/5acda6ed-2c90-4ec9-9303-5f3d0cddced7">
<img width="805" alt="Screenshot 2024-06-29 at 10 52 36" src="https://github.com/beyondcode/herd-community/assets/19960361/289907cc-5bdd-45ce-b7ee-f91d210e86e8">

**Comment by sschlein** [comment]
Could you please check your config directory for Herd? I have attached a screenshot about the things that I am interested in. There should be a services JSON with the services and a directory that holds the data of these services, so your MySQL databases should still be there. If you create a new MySQL service and move the old data over while both processes are stopped, that should bring them back.

Please share your services-plist file or it's content so that we can have a look. I can't come up with a reason why Herd would start mysql on the postgres port but I can obviously see that from your terminal output 🤔


![CleanShot 2024-07-01 at 08 12 42](https://github.com/beyondcode/herd-community/assets/2911113/49f2936d-24aa-4992-888b-d2500fcc1254)
