### ISSUE TITLE
[Bug]: herd share / expose share fails after 1 second

### ISSUE THREAD

**Issue by MrMooky** [beyondcode/herd-community#918]
### Platform

macOS

### Operating system version

macOS 14.5 (23F79)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.9.1 (Build 31)

### Bug description

When calling `herd share`, I get a `302 GET /` and then it instantly stops the process as if it never was started.

![Screenshot 2024-08-06 at 09 27 34](https://github.com/user-attachments/assets/2c3ec3ac-98b0-42e9-8e56-7cfae755c7f8)

Also tried `expose share https://local-domain.test`, but this ends in the same result.

**Comment by MrMooky** [comment]
I created a new, fresh project and ran `herd share`. It did not fail. But after running it again, the same error as reported appears. It essentially happens for all projects. But some are responding with `302 GET /` and some with `200 GET /`.

**Comment by MrMooky** [comment]
What bothers me A LOT right now is the fact that my fallback solution with ngrok also does not work as the tunnel url shows a Herd "Site not found" message. Had no issues with this last week. I can't remember running any Herd updates, and I did not run any other updates. So it's essentially the exact same setup as last week when it was still working. ._.

**Comment by mpociot** [comment]
@MrMooky do you happen to have a minute to share your screen via Google Meet/Tuple? 
I have no clue how to reproduce this locally.

**Comment by MrMooky** [comment]
Yes, sure. Feel free to send me an invitation to andreas@stella-projects.de

**Comment by mpociot** [comment]
Okay - I finally figured out what's going on here.

This is a curl bug that was introduced in version 8.9.0 of curl itself and is already fixed in the latest unreleased version of curl.
As the latest version of PHP uses curl 8.9.1 this error occurs.

I will publish a new PHP Update that downgrades curl from 8.9.1 to the working version 8.8.0, as the next curl update is scheduled for release in September and we don't want to have Expose broken for so long.

I'll close this issue as soon as the new PHP updates are available.

**Comment by MrMooky** [comment]
Perfect, thanks for digging into that. :) Just out of curiosity, which version is PHP 8.3 using? As we saw that this worked.

**Comment by mpociot** [comment]
The current version available in Herd is using curl 8.8.0

**Comment by mpociot** [comment]
The PHP 8.3 and 8.2 updates are now published. The ARM64 versions are already out, the Intel versions are available in a couple of minutes.
