### ISSUE TITLE
[Bug]: PHP versions behind (8.2, 8.3 & 8.4)

### ISSUE THREAD

**Issue by ultimateBusiness** [beyondcode/herd-community#968]
### Platform

macOS

### Operating system version

macOS 14.6.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.9.1

### Bug description

As every time new releases of PHP are out - it is not possible to update in Herd for a long time (until someone is crying - like me).
For Node it seems to work just in time - why is there a problem with PHP?

**Comment by sschlein** [comment]
Herd uses statically compiled binaries for PHP (and doesn't for node) and they aren't provided by the php foundation. So we need to compile them for all macOS versions on Intel and Apple Silicon chips and that's not as easy as running a single command. Most of the time, there are changes and patches required so that a version is statically compilable. We've PRd these changes last week but they aren't through the whole process yet. 

These static binaries are the reason why php updates are so easy with Herd but run into issues with Homebrew quite often, they are also more than 30% faster than regular versions. 

I've written more about that in the docs that we plan to release with the next Herd version in 1-2 weeks. 

If you rely on immediate updates for PHP patch versions, Herd is probably not for you because we can't guarantee them.
